In [29]:
import h5py
import numpy as np

# Open an h5 file in read mode
file_path = 'data/hBreast/cell_feature_matrix.h5'  # Replace 'your_file.h5' with the path to your h5 file
with h5py.File(file_path, 'r') as h5_file:
    dataset_name = list(h5_file.keys())[0]  # Get the name of the first dataset
    dataset = h5_file["/matrix/features"]  # Access the dataset
    print(dataset.keys())
    for key in dataset.keys():
        print(key)
        print(dataset[key][:5])
        print(len(np.unique(dataset[key][:])))
    print(dataset["feature_type"][:])

<KeysViewHDF5 ['_all_tag_keys', 'feature_type', 'genome', 'id', 'name']>
_all_tag_keys
[b'genome']
1
feature_type
[b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression']
4
genome
[b'Unknown' b'Unknown' b'Unknown' b'Unknown' b'Unknown']
1
id
[b'ENSG00000121270' b'ENSG00000107796' b'ENSG00000163017'
 b'ENSG00000168615' b'ENSG00000123146']
541
name
[b'ABCC11' b'ACTA2' b'ACTG2' b'ADAM9' b'ADGRE5']
541
[b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expression' b'Gene Expression'
 b'Gene Expression' b'Gene Expressi

In [39]:
import gzip
import pandas as pd

# Define the path to the .tsv.gz file
tsv_gz_file_path = 'data/hBreast/cell_feature_matrix/features.tsv.gz'  # Replace with the path to your .tsv.gz file

# Open and read the .tsv.gz file
with gzip.open(tsv_gz_file_path, 'rt') as file:
    # Read the file into a pandas DataFrame
    df = pd.read_csv(file, delimiter='\t')
    
    # Display the first few rows of the DataFrame
    print(df.head(25))


     %%MatrixMarket matrix coordinate integer general
0   %metadata_json: {"software_version": "xenium u...
1                                 541 356746 15571173
2                                               2 1 2
3                                               4 1 1
4                                               6 1 9
5                                              26 1 1
6                                             36 1 10
7                                              39 1 1
8                                              59 1 1
9                                              71 1 1
10                                             75 1 1
11                                            77 1 18
12                                             86 1 7
13                                             89 1 1
14                                             93 1 2
15                                             98 1 1
16                                            104 1 4
17                          

In [40]:
import gzip
import pandas as pd
from scipy.io import mmread

# Define the path to the .mtx.gz file
mtx_gz_file_path = 'data/hBreast/cell_feature_matrix/matrix.mtx.gz'  # Replace with the path to your .mtx.gz file

# Open and read the .mtx.gz file
with gzip.open(mtx_gz_file_path, 'rt') as file:
    # Read the file into a sparse matrix
    sparse_matrix = mmread(file)
    
    # Convert the sparse matrix to a dense format (if needed)
    dense_matrix = sparse_matrix.toarray()
    
    # Display the shape of the matrix
    print("Matrix shape:", dense_matrix.shape)
    
    # Display the first few rows of the matrix
    print(dense_matrix[:5, :5])


Matrix shape: (541, 356746)
[[0 0 0 0 0]
 [2 0 1 2 0]
 [0 0 0 1 0]
 [1 1 0 0 2]
 [0 2 0 0 0]]
